# WebDriver configuration
[drivers]
# How many drivers are available at a time. If none are available when a fetch
# is tried, the thread will simply spin.
driver_count = 9

# The program allocates ports linearly. This is the base port for the
# allocation. i.e the first port will be `base_port`, then the second will be
# `base_port + 1`
base_port = 8444

# Configuring how post fetches should be performed
[fetch]
# When fetching a user's timeline (when updating it), how many links to collect
# This is a minimum, as fetching doesn't stop until the last tweet fetched is
# not a retweet.
max_links_per_fetch = 5

# When fetching multiple users' timelines concurrently, how many active user
# fetches should be active at a time
max_concurrent_users = 3

# When fetching a user's timeline, how many posts to fetch concurrently
max_sessions_per_user = 3

# Get all "following" from this user, and fetch the data from every user
fetch_username = "gooseiman"

# When fetching data by scrolling, max times that the operation should be
# retried when there is no change
max_retries = 5

# Twitter conf
[twitter]
# Filename for caching the auth cookie for twitter
auth_cache_fname = "cached_auth"

# The classes needed to identify an element
[twitter.css_classes]
following_users = ["css-4rbku5", "css-18t94o4", "r-1loqt21", "r-1wbh5a2"]
user_info = ["css-1dbjc4n", "r-1ifxtd0", "r-ymttw5", "r-ttdzmv"]
user_description = ["css-1dbjc4n", "r-1adg3ll", "r-6gpygo"]
user_name = ["css-1dbjc4n", "r-6gpygo", "r-14gqq1x"]

[twitter.xpaths]
banner_img = "/html/body/div[1]/div/div/div[2]/main/div/div/div/div/div/div/div/div/div/a/div/div[2]/div/img"
banner_exit = "/html/body/div[1]/div/div/div[1]/div[2]/div/div/div/div/div/div[2]/div[2]/div[2]/div/div"
